//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSignageUI.TvsServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TvsInfoWTO", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class TvsInfoWTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long alarm_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long category_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int content_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int isDirtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long lastAliveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int xField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long alarm_id {
            get {
                return this.alarm_idField;
            }
            set {
                if ((this.alarm_idField.Equals(value) != true)) {
                    this.alarm_idField = value;
                    this.RaisePropertyChanged("alarm_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long category_id {
            get {
                return this.category_idField;
            }
            set {
                if ((this.category_idField.Equals(value) != true)) {
                    this.category_idField = value;
                    this.RaisePropertyChanged("category_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int content_id {
            get {
                return this.content_idField;
            }
            set {
                if ((this.content_idField.Equals(value) != true)) {
                    this.content_idField = value;
                    this.RaisePropertyChanged("content_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                if ((object.ReferenceEquals(this.ipField, value) != true)) {
                    this.ipField = value;
                    this.RaisePropertyChanged("ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int isDirty {
            get {
                return this.isDirtyField;
            }
            set {
                if ((this.isDirtyField.Equals(value) != true)) {
                    this.isDirtyField = value;
                    this.RaisePropertyChanged("isDirty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long lastAlive {
            get {
                return this.lastAliveField;
            }
            set {
                if ((this.lastAliveField.Equals(value) != true)) {
                    this.lastAliveField = value;
                    this.RaisePropertyChanged("lastAlive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultMessageOfstring", Namespace="http://schemas.datacontract.org/2004/07/Aryaban.Engine.Core.WebService")]
    [System.SerializableAttribute()]
    public partial class ResultMessageOfstring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.TvsServices.Result resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.TvsServices.Result result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultSet {
            get {
                return this.resultSetField;
            }
            set {
                if ((object.ReferenceEquals(this.resultSetField, value) != true)) {
                    this.resultSetField = value;
                    this.RaisePropertyChanged("resultSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/Aryaban.Engine.Core.WebService")]
    [System.SerializableAttribute()]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string callbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string redirectUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.TvsServices.Result.state statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string callback {
            get {
                return this.callbackField;
            }
            set {
                if ((object.ReferenceEquals(this.callbackField, value) != true)) {
                    this.callbackField = value;
                    this.RaisePropertyChanged("callback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string redirectUrl {
            get {
                return this.redirectUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.redirectUrlField, value) != true)) {
                    this.redirectUrlField = value;
                    this.RaisePropertyChanged("redirectUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.TvsServices.Result.state status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Result.state", Namespace="http://schemas.datacontract.org/2004/07/Aryaban.Engine.Core.WebService")]
        public enum state : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            error = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            success = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            warning = 2,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TvCategoreisInfoWTO", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class TvCategoreisInfoWTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long parent_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long parent_id {
            get {
                return this.parent_idField;
            }
            set {
                if ((this.parent_idField.Equals(value) != true)) {
                    this.parent_idField = value;
                    this.RaisePropertyChanged("parent_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultMessageOfboolean", Namespace="http://schemas.datacontract.org/2004/07/Aryaban.Engine.Core.WebService")]
    [System.SerializableAttribute()]
    public partial class ResultMessageOfboolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.TvsServices.Result resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool resultSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.TvsServices.Result result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool resultSet {
            get {
                return this.resultSetField;
            }
            set {
                if ((this.resultSetField.Equals(value) != true)) {
                    this.resultSetField = value;
                    this.RaisePropertyChanged("resultSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingInfo", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class PagingInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.TvsServices.OrderInfo[] orderLstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.TvsServices.OrderInfo[] orderLst {
            get {
                return this.orderLstField;
            }
            set {
                if ((object.ReferenceEquals(this.orderLstField, value) != true)) {
                    this.orderLstField = value;
                    this.RaisePropertyChanged("orderLst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                if ((this.pageNumberField.Equals(value) != true)) {
                    this.pageNumberField = value;
                    this.RaisePropertyChanged("pageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                if ((this.pageSizeField.Equals(value) != true)) {
                    this.pageSizeField = value;
                    this.RaisePropertyChanged("pageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderInfo", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class OrderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sortTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderName {
            get {
                return this.orderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.orderNameField, value) != true)) {
                    this.orderNameField = value;
                    this.RaisePropertyChanged("orderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sortType {
            get {
                return this.sortTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.sortTypeField, value) != true)) {
                    this.sortTypeField = value;
                    this.RaisePropertyChanged("sortType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultMessageOfArrayOfTvCategoreisInfoWTONurSmnnE", Namespace="http://schemas.datacontract.org/2004/07/Aryaban.Engine.Core.WebService")]
    [System.SerializableAttribute()]
    public partial class ResultMessageOfArrayOfTvCategoreisInfoWTONurSmnnE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.TvsServices.Result resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.TvsServices.TvCategoreisInfoWTO[] resultSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.TvsServices.Result result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.TvsServices.TvCategoreisInfoWTO[] resultSet {
            get {
                return this.resultSetField;
            }
            set {
                if ((object.ReferenceEquals(this.resultSetField, value) != true)) {
                    this.resultSetField = value;
                    this.RaisePropertyChanged("resultSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultMessageOfArrayOfTvsInfoWTONurSmnnE", Namespace="http://schemas.datacontract.org/2004/07/Aryaban.Engine.Core.WebService")]
    [System.SerializableAttribute()]
    public partial class ResultMessageOfArrayOfTvsInfoWTONurSmnnE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.TvsServices.Result resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.TvsServices.TvsInfoWTO[] resultSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.TvsServices.Result result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.TvsServices.TvsInfoWTO[] resultSet {
            get {
                return this.resultSetField;
            }
            set {
                if ((object.ReferenceEquals(this.resultSetField, value) != true)) {
                    this.resultSetField = value;
                    this.RaisePropertyChanged("resultSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TvsServices.Itvs")]
    public interface Itvs {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/addTV", ReplyAction="http://tempuri.org/Itvs/addTVResponse")]
        DigitalSignageUI.TvsServices.ResultMessageOfstring addTV(DigitalSignageUI.TvsServices.TvsInfoWTO tvsInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/addTV", ReplyAction="http://tempuri.org/Itvs/addTVResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfstring> addTVAsync(DigitalSignageUI.TvsServices.TvsInfoWTO tvsInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/editTV", ReplyAction="http://tempuri.org/Itvs/editTVResponse")]
        DigitalSignageUI.TvsServices.ResultMessageOfstring editTV(DigitalSignageUI.TvsServices.TvsInfoWTO tvsInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/editTV", ReplyAction="http://tempuri.org/Itvs/editTVResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfstring> editTVAsync(DigitalSignageUI.TvsServices.TvsInfoWTO tvsInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/addCategory", ReplyAction="http://tempuri.org/Itvs/addCategoryResponse")]
        DigitalSignageUI.TvsServices.ResultMessageOfstring addCategory(DigitalSignageUI.TvsServices.TvCategoreisInfoWTO tvCategoreisInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/addCategory", ReplyAction="http://tempuri.org/Itvs/addCategoryResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfstring> addCategoryAsync(DigitalSignageUI.TvsServices.TvCategoreisInfoWTO tvCategoreisInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/deleteTVS", ReplyAction="http://tempuri.org/Itvs/deleteTVSResponse")]
        DigitalSignageUI.TvsServices.ResultMessageOfstring deleteTVS(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/deleteTVS", ReplyAction="http://tempuri.org/Itvs/deleteTVSResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfstring> deleteTVSAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/deleteCategory", ReplyAction="http://tempuri.org/Itvs/deleteCategoryResponse")]
        DigitalSignageUI.TvsServices.ResultMessageOfstring deleteCategory(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/deleteCategory", ReplyAction="http://tempuri.org/Itvs/deleteCategoryResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfstring> deleteCategoryAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/isDirty", ReplyAction="http://tempuri.org/Itvs/isDirtyResponse")]
        DigitalSignageUI.TvsServices.ResultMessageOfboolean isDirty(long tv_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/isDirty", ReplyAction="http://tempuri.org/Itvs/isDirtyResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfboolean> isDirtyAsync(long tv_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/recordSecondPlayed", ReplyAction="http://tempuri.org/Itvs/recordSecondPlayedResponse")]
        DigitalSignageUI.TvsServices.ResultMessageOfboolean recordSecondPlayed(long content_ad_id, long tv_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/recordSecondPlayed", ReplyAction="http://tempuri.org/Itvs/recordSecondPlayedResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfboolean> recordSecondPlayedAsync(long content_ad_id, long tv_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/searchDataOnTvCategories", ReplyAction="http://tempuri.org/Itvs/searchDataOnTvCategoriesResponse")]
        DigitalSignageUI.TvsServices.ResultMessageOfArrayOfTvCategoreisInfoWTONurSmnnE searchDataOnTvCategories(DigitalSignageUI.TvsServices.TvCategoreisInfoWTO filter, DigitalSignageUI.TvsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/searchDataOnTvCategories", ReplyAction="http://tempuri.org/Itvs/searchDataOnTvCategoriesResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfArrayOfTvCategoreisInfoWTONurSmnnE> searchDataOnTvCategoriesAsync(DigitalSignageUI.TvsServices.TvCategoreisInfoWTO filter, DigitalSignageUI.TvsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/searchDataOnTvs", ReplyAction="http://tempuri.org/Itvs/searchDataOnTvsResponse")]
        DigitalSignageUI.TvsServices.ResultMessageOfArrayOfTvsInfoWTONurSmnnE searchDataOnTvs(DigitalSignageUI.TvsServices.TvsInfoWTO filter, DigitalSignageUI.TvsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/searchDataOnTvs", ReplyAction="http://tempuri.org/Itvs/searchDataOnTvsResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfArrayOfTvsInfoWTONurSmnnE> searchDataOnTvsAsync(DigitalSignageUI.TvsServices.TvsInfoWTO filter, DigitalSignageUI.TvsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/getTvContentWithIp", ReplyAction="http://tempuri.org/Itvs/getTvContentWithIpResponse")]
        DigitalSignageUI.TvsServices.ResultMessageOfstring getTvContentWithIp(string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itvs/getTvContentWithIp", ReplyAction="http://tempuri.org/Itvs/getTvContentWithIpResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfstring> getTvContentWithIpAsync(string ip);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ItvsChannel : DigitalSignageUI.TvsServices.Itvs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItvsClient : System.ServiceModel.ClientBase<DigitalSignageUI.TvsServices.Itvs>, DigitalSignageUI.TvsServices.Itvs {
        
        public ItvsClient() {
        }
        
        public ItvsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItvsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItvsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItvsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DigitalSignageUI.TvsServices.ResultMessageOfstring addTV(DigitalSignageUI.TvsServices.TvsInfoWTO tvsInfo) {
            return base.Channel.addTV(tvsInfo);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfstring> addTVAsync(DigitalSignageUI.TvsServices.TvsInfoWTO tvsInfo) {
            return base.Channel.addTVAsync(tvsInfo);
        }
        
        public DigitalSignageUI.TvsServices.ResultMessageOfstring editTV(DigitalSignageUI.TvsServices.TvsInfoWTO tvsInfo) {
            return base.Channel.editTV(tvsInfo);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfstring> editTVAsync(DigitalSignageUI.TvsServices.TvsInfoWTO tvsInfo) {
            return base.Channel.editTVAsync(tvsInfo);
        }
        
        public DigitalSignageUI.TvsServices.ResultMessageOfstring addCategory(DigitalSignageUI.TvsServices.TvCategoreisInfoWTO tvCategoreisInfo) {
            return base.Channel.addCategory(tvCategoreisInfo);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfstring> addCategoryAsync(DigitalSignageUI.TvsServices.TvCategoreisInfoWTO tvCategoreisInfo) {
            return base.Channel.addCategoryAsync(tvCategoreisInfo);
        }
        
        public DigitalSignageUI.TvsServices.ResultMessageOfstring deleteTVS(long id) {
            return base.Channel.deleteTVS(id);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfstring> deleteTVSAsync(long id) {
            return base.Channel.deleteTVSAsync(id);
        }
        
        public DigitalSignageUI.TvsServices.ResultMessageOfstring deleteCategory(long id) {
            return base.Channel.deleteCategory(id);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfstring> deleteCategoryAsync(long id) {
            return base.Channel.deleteCategoryAsync(id);
        }
        
        public DigitalSignageUI.TvsServices.ResultMessageOfboolean isDirty(long tv_id) {
            return base.Channel.isDirty(tv_id);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfboolean> isDirtyAsync(long tv_id) {
            return base.Channel.isDirtyAsync(tv_id);
        }
        
        public DigitalSignageUI.TvsServices.ResultMessageOfboolean recordSecondPlayed(long content_ad_id, long tv_id) {
            return base.Channel.recordSecondPlayed(content_ad_id, tv_id);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfboolean> recordSecondPlayedAsync(long content_ad_id, long tv_id) {
            return base.Channel.recordSecondPlayedAsync(content_ad_id, tv_id);
        }
        
        public DigitalSignageUI.TvsServices.ResultMessageOfArrayOfTvCategoreisInfoWTONurSmnnE searchDataOnTvCategories(DigitalSignageUI.TvsServices.TvCategoreisInfoWTO filter, DigitalSignageUI.TvsServices.PagingInfo paging) {
            return base.Channel.searchDataOnTvCategories(filter, paging);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfArrayOfTvCategoreisInfoWTONurSmnnE> searchDataOnTvCategoriesAsync(DigitalSignageUI.TvsServices.TvCategoreisInfoWTO filter, DigitalSignageUI.TvsServices.PagingInfo paging) {
            return base.Channel.searchDataOnTvCategoriesAsync(filter, paging);
        }
        
        public DigitalSignageUI.TvsServices.ResultMessageOfArrayOfTvsInfoWTONurSmnnE searchDataOnTvs(DigitalSignageUI.TvsServices.TvsInfoWTO filter, DigitalSignageUI.TvsServices.PagingInfo paging) {
            return base.Channel.searchDataOnTvs(filter, paging);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfArrayOfTvsInfoWTONurSmnnE> searchDataOnTvsAsync(DigitalSignageUI.TvsServices.TvsInfoWTO filter, DigitalSignageUI.TvsServices.PagingInfo paging) {
            return base.Channel.searchDataOnTvsAsync(filter, paging);
        }
        
        public DigitalSignageUI.TvsServices.ResultMessageOfstring getTvContentWithIp(string ip) {
            return base.Channel.getTvContentWithIp(ip);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.TvsServices.ResultMessageOfstring> getTvContentWithIpAsync(string ip) {
            return base.Channel.getTvContentWithIpAsync(ip);
        }
    }
}
