//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSignageUI.ContentsServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentInfoWTO", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class ContentInfoWTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ad_titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long content_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int durationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int endTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string file_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long lastViewedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int startTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long tv_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ad_title {
            get {
                return this.ad_titleField;
            }
            set {
                if ((object.ReferenceEquals(this.ad_titleField, value) != true)) {
                    this.ad_titleField = value;
                    this.RaisePropertyChanged("ad_title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long content_id {
            get {
                return this.content_idField;
            }
            set {
                if ((this.content_idField.Equals(value) != true)) {
                    this.content_idField = value;
                    this.RaisePropertyChanged("content_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int duration {
            get {
                return this.durationField;
            }
            set {
                if ((this.durationField.Equals(value) != true)) {
                    this.durationField = value;
                    this.RaisePropertyChanged("duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int endTime {
            get {
                return this.endTimeField;
            }
            set {
                if ((this.endTimeField.Equals(value) != true)) {
                    this.endTimeField = value;
                    this.RaisePropertyChanged("endTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string file_name {
            get {
                return this.file_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.file_nameField, value) != true)) {
                    this.file_nameField = value;
                    this.RaisePropertyChanged("file_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long lastViewed {
            get {
                return this.lastViewedField;
            }
            set {
                if ((this.lastViewedField.Equals(value) != true)) {
                    this.lastViewedField = value;
                    this.RaisePropertyChanged("lastViewed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int startTime {
            get {
                return this.startTimeField;
            }
            set {
                if ((this.startTimeField.Equals(value) != true)) {
                    this.startTimeField = value;
                    this.RaisePropertyChanged("startTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long tv_id {
            get {
                return this.tv_idField;
            }
            set {
                if ((this.tv_idField.Equals(value) != true)) {
                    this.tv_idField = value;
                    this.RaisePropertyChanged("tv_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentOptionInfoWTO", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class ContentOptionInfoWTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ad_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long content_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long createDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long live_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int positionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int secondField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int secondViewedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int shuffleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ad_id {
            get {
                return this.ad_idField;
            }
            set {
                if ((this.ad_idField.Equals(value) != true)) {
                    this.ad_idField = value;
                    this.RaisePropertyChanged("ad_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long content_id {
            get {
                return this.content_idField;
            }
            set {
                if ((this.content_idField.Equals(value) != true)) {
                    this.content_idField = value;
                    this.RaisePropertyChanged("content_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long createDateTime {
            get {
                return this.createDateTimeField;
            }
            set {
                if ((this.createDateTimeField.Equals(value) != true)) {
                    this.createDateTimeField = value;
                    this.RaisePropertyChanged("createDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int interval {
            get {
                return this.intervalField;
            }
            set {
                if ((this.intervalField.Equals(value) != true)) {
                    this.intervalField = value;
                    this.RaisePropertyChanged("interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long live_id {
            get {
                return this.live_idField;
            }
            set {
                if ((this.live_idField.Equals(value) != true)) {
                    this.live_idField = value;
                    this.RaisePropertyChanged("live_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int position {
            get {
                return this.positionField;
            }
            set {
                if ((this.positionField.Equals(value) != true)) {
                    this.positionField = value;
                    this.RaisePropertyChanged("position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int second {
            get {
                return this.secondField;
            }
            set {
                if ((this.secondField.Equals(value) != true)) {
                    this.secondField = value;
                    this.RaisePropertyChanged("second");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int secondViewed {
            get {
                return this.secondViewedField;
            }
            set {
                if ((this.secondViewedField.Equals(value) != true)) {
                    this.secondViewedField = value;
                    this.RaisePropertyChanged("secondViewed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int shuffle {
            get {
                return this.shuffleField;
            }
            set {
                if ((this.shuffleField.Equals(value) != true)) {
                    this.shuffleField = value;
                    this.RaisePropertyChanged("shuffle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdsInfoWTO", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class AdsInfoWTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adItemDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adItemFeedTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adItemFeedUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adItemImageFileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adItemTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adItemVedioFileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long content_ad_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.ContentsServices.AdsIemInfoWTO[] itemListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int max_minutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int passed_minutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int positionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int shuffleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adItemDesc {
            get {
                return this.adItemDescField;
            }
            set {
                if ((object.ReferenceEquals(this.adItemDescField, value) != true)) {
                    this.adItemDescField = value;
                    this.RaisePropertyChanged("adItemDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adItemFeedTitle {
            get {
                return this.adItemFeedTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.adItemFeedTitleField, value) != true)) {
                    this.adItemFeedTitleField = value;
                    this.RaisePropertyChanged("adItemFeedTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adItemFeedUrl {
            get {
                return this.adItemFeedUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.adItemFeedUrlField, value) != true)) {
                    this.adItemFeedUrlField = value;
                    this.RaisePropertyChanged("adItemFeedUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adItemImageFileName {
            get {
                return this.adItemImageFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.adItemImageFileNameField, value) != true)) {
                    this.adItemImageFileNameField = value;
                    this.RaisePropertyChanged("adItemImageFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adItemTitle {
            get {
                return this.adItemTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.adItemTitleField, value) != true)) {
                    this.adItemTitleField = value;
                    this.RaisePropertyChanged("adItemTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adItemVedioFileName {
            get {
                return this.adItemVedioFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.adItemVedioFileNameField, value) != true)) {
                    this.adItemVedioFileNameField = value;
                    this.RaisePropertyChanged("adItemVedioFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long content_ad_id {
            get {
                return this.content_ad_idField;
            }
            set {
                if ((this.content_ad_idField.Equals(value) != true)) {
                    this.content_ad_idField = value;
                    this.RaisePropertyChanged("content_ad_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int interval {
            get {
                return this.intervalField;
            }
            set {
                if ((this.intervalField.Equals(value) != true)) {
                    this.intervalField = value;
                    this.RaisePropertyChanged("interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.ContentsServices.AdsIemInfoWTO[] itemList {
            get {
                return this.itemListField;
            }
            set {
                if ((object.ReferenceEquals(this.itemListField, value) != true)) {
                    this.itemListField = value;
                    this.RaisePropertyChanged("itemList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int max_minutes {
            get {
                return this.max_minutesField;
            }
            set {
                if ((this.max_minutesField.Equals(value) != true)) {
                    this.max_minutesField = value;
                    this.RaisePropertyChanged("max_minutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int passed_minutes {
            get {
                return this.passed_minutesField;
            }
            set {
                if ((this.passed_minutesField.Equals(value) != true)) {
                    this.passed_minutesField = value;
                    this.RaisePropertyChanged("passed_minutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int position {
            get {
                return this.positionField;
            }
            set {
                if ((this.positionField.Equals(value) != true)) {
                    this.positionField = value;
                    this.RaisePropertyChanged("position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int shuffle {
            get {
                return this.shuffleField;
            }
            set {
                if ((this.shuffleField.Equals(value) != true)) {
                    this.shuffleField = value;
                    this.RaisePropertyChanged("shuffle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdsIemInfoWTO", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class AdsIemInfoWTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ad_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long datetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string file_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int minutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ad_id {
            get {
                return this.ad_idField;
            }
            set {
                if ((this.ad_idField.Equals(value) != true)) {
                    this.ad_idField = value;
                    this.RaisePropertyChanged("ad_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long datetime {
            get {
                return this.datetimeField;
            }
            set {
                if ((this.datetimeField.Equals(value) != true)) {
                    this.datetimeField = value;
                    this.RaisePropertyChanged("datetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string file_name {
            get {
                return this.file_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.file_nameField, value) != true)) {
                    this.file_nameField = value;
                    this.RaisePropertyChanged("file_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int minutes {
            get {
                return this.minutesField;
            }
            set {
                if ((this.minutesField.Equals(value) != true)) {
                    this.minutesField = value;
                    this.RaisePropertyChanged("minutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LiveTVInfoWTO", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class LiveTVInfoWTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string channelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long content_ad_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int positionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string channel {
            get {
                return this.channelField;
            }
            set {
                if ((object.ReferenceEquals(this.channelField, value) != true)) {
                    this.channelField = value;
                    this.RaisePropertyChanged("channel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long content_ad_id {
            get {
                return this.content_ad_idField;
            }
            set {
                if ((this.content_ad_idField.Equals(value) != true)) {
                    this.content_ad_idField = value;
                    this.RaisePropertyChanged("content_ad_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int interval {
            get {
                return this.intervalField;
            }
            set {
                if ((this.intervalField.Equals(value) != true)) {
                    this.intervalField = value;
                    this.RaisePropertyChanged("interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int position {
            get {
                return this.positionField;
            }
            set {
                if ((this.positionField.Equals(value) != true)) {
                    this.positionField = value;
                    this.RaisePropertyChanged("position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingInfo", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class PagingInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.ContentsServices.OrderInfo[] orderLstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.ContentsServices.OrderInfo[] orderLst {
            get {
                return this.orderLstField;
            }
            set {
                if ((object.ReferenceEquals(this.orderLstField, value) != true)) {
                    this.orderLstField = value;
                    this.RaisePropertyChanged("orderLst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                if ((this.pageNumberField.Equals(value) != true)) {
                    this.pageNumberField = value;
                    this.RaisePropertyChanged("pageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                if ((this.pageSizeField.Equals(value) != true)) {
                    this.pageSizeField = value;
                    this.RaisePropertyChanged("pageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderInfo", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class OrderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sortTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderName {
            get {
                return this.orderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.orderNameField, value) != true)) {
                    this.orderNameField = value;
                    this.RaisePropertyChanged("orderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sortType {
            get {
                return this.sortTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.sortTypeField, value) != true)) {
                    this.sortTypeField = value;
                    this.RaisePropertyChanged("sortType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentTypeWTO", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class ContentTypeWTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string file_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string body {
            get {
                return this.bodyField;
            }
            set {
                if ((object.ReferenceEquals(this.bodyField, value) != true)) {
                    this.bodyField = value;
                    this.RaisePropertyChanged("body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string file_name {
            get {
                return this.file_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.file_nameField, value) != true)) {
                    this.file_nameField = value;
                    this.RaisePropertyChanged("file_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ContentsServices.Icontents")]
    public interface Icontents {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/getNewContentId", ReplyAction="http://tempuri.org/Icontents/getNewContentIdResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<int> getNewContentId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/getNewContentId", ReplyAction="http://tempuri.org/Icontents/getNewContentIdResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<int>> getNewContentIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/addContent", ReplyAction="http://tempuri.org/Icontents/addContentResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<string> addContent(DigitalSignageUI.ContentsServices.ContentInfoWTO contentInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/addContent", ReplyAction="http://tempuri.org/Icontents/addContentResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> addContentAsync(DigitalSignageUI.ContentsServices.ContentInfoWTO contentInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/editContentOption", ReplyAction="http://tempuri.org/Icontents/editContentOptionResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<string> editContentOption(DigitalSignageUI.ContentsServices.ContentOptionInfoWTO contentOptionInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/editContentOption", ReplyAction="http://tempuri.org/Icontents/editContentOptionResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> editContentOptionAsync(DigitalSignageUI.ContentsServices.ContentOptionInfoWTO contentOptionInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/editContentOptionLive", ReplyAction="http://tempuri.org/Icontents/editContentOptionLiveResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<string> editContentOptionLive(DigitalSignageUI.ContentsServices.ContentOptionInfoWTO contentOptionInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/editContentOptionLive", ReplyAction="http://tempuri.org/Icontents/editContentOptionLiveResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> editContentOptionLiveAsync(DigitalSignageUI.ContentsServices.ContentOptionInfoWTO contentOptionInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/deleteContents", ReplyAction="http://tempuri.org/Icontents/deleteContentsResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<string> deleteContents(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/deleteContents", ReplyAction="http://tempuri.org/Icontents/deleteContentsResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> deleteContentsAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/editContentAds", ReplyAction="http://tempuri.org/Icontents/editContentAdsResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<string> editContentAds(DigitalSignageUI.ContentsServices.ContentOptionInfoWTO contentOptionInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/editContentAds", ReplyAction="http://tempuri.org/Icontents/editContentAdsResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> editContentAdsAsync(DigitalSignageUI.ContentsServices.ContentOptionInfoWTO contentOptionInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/searchContentsWithAdsItemDetail", ReplyAction="http://tempuri.org/Icontents/searchContentsWithAdsItemDetailResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.AdsInfoWTO[]> searchContentsWithAdsItemDetail(string type, long content_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/searchContentsWithAdsItemDetail", ReplyAction="http://tempuri.org/Icontents/searchContentsWithAdsItemDetailResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.AdsInfoWTO[]>> searchContentsWithAdsItemDetailAsync(string type, long content_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/loadContentsWithAdsItemDetail", ReplyAction="http://tempuri.org/Icontents/loadContentsWithAdsItemDetailResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.AdsInfoWTO[]> loadContentsWithAdsItemDetail(long content_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/loadContentsWithAdsItemDetail", ReplyAction="http://tempuri.org/Icontents/loadContentsWithAdsItemDetailResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.AdsInfoWTO[]>> loadContentsWithAdsItemDetailAsync(long content_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/loadLiveContentsAds", ReplyAction="http://tempuri.org/Icontents/loadLiveContentsAdsResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.LiveTVInfoWTO[]> loadLiveContentsAds(long content_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/loadLiveContentsAds", ReplyAction="http://tempuri.org/Icontents/loadLiveContentsAdsResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.LiveTVInfoWTO[]>> loadLiveContentsAdsAsync(long content_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/getContentList", ReplyAction="http://tempuri.org/Icontents/getContentListResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.ContentInfoWTO[]> getContentList(DigitalSignageUI.ContentsServices.ContentInfoWTO filter, DigitalSignageUI.ContentsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/getContentList", ReplyAction="http://tempuri.org/Icontents/getContentListResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.ContentInfoWTO[]>> getContentListAsync(DigitalSignageUI.ContentsServices.ContentInfoWTO filter, DigitalSignageUI.ContentsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/searchDataContent", ReplyAction="http://tempuri.org/Icontents/searchDataContentResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.ContentInfoWTO[]> searchDataContent(DigitalSignageUI.ContentsServices.ContentInfoWTO filter, DigitalSignageUI.ContentsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/searchDataContent", ReplyAction="http://tempuri.org/Icontents/searchDataContentResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.ContentInfoWTO[]>> searchDataContentAsync(DigitalSignageUI.ContentsServices.ContentInfoWTO filter, DigitalSignageUI.ContentsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/searchDataContentType", ReplyAction="http://tempuri.org/Icontents/searchDataContentTypeResponse")]
        Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.ContentTypeWTO[]> searchDataContentType(DigitalSignageUI.ContentsServices.ContentTypeWTO filter, DigitalSignageUI.ContentsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Icontents/searchDataContentType", ReplyAction="http://tempuri.org/Icontents/searchDataContentTypeResponse")]
        System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.ContentTypeWTO[]>> searchDataContentTypeAsync(DigitalSignageUI.ContentsServices.ContentTypeWTO filter, DigitalSignageUI.ContentsServices.PagingInfo paging);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IcontentsChannel : DigitalSignageUI.ContentsServices.Icontents, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IcontentsClient : System.ServiceModel.ClientBase<DigitalSignageUI.ContentsServices.Icontents>, DigitalSignageUI.ContentsServices.Icontents {
        
        public IcontentsClient() {
        }
        
        public IcontentsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IcontentsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IcontentsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IcontentsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<int> getNewContentId() {
            return base.Channel.getNewContentId();
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<int>> getNewContentIdAsync() {
            return base.Channel.getNewContentIdAsync();
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<string> addContent(DigitalSignageUI.ContentsServices.ContentInfoWTO contentInfo) {
            return base.Channel.addContent(contentInfo);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> addContentAsync(DigitalSignageUI.ContentsServices.ContentInfoWTO contentInfo) {
            return base.Channel.addContentAsync(contentInfo);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<string> editContentOption(DigitalSignageUI.ContentsServices.ContentOptionInfoWTO contentOptionInfo) {
            return base.Channel.editContentOption(contentOptionInfo);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> editContentOptionAsync(DigitalSignageUI.ContentsServices.ContentOptionInfoWTO contentOptionInfo) {
            return base.Channel.editContentOptionAsync(contentOptionInfo);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<string> editContentOptionLive(DigitalSignageUI.ContentsServices.ContentOptionInfoWTO contentOptionInfo) {
            return base.Channel.editContentOptionLive(contentOptionInfo);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> editContentOptionLiveAsync(DigitalSignageUI.ContentsServices.ContentOptionInfoWTO contentOptionInfo) {
            return base.Channel.editContentOptionLiveAsync(contentOptionInfo);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<string> deleteContents(long id) {
            return base.Channel.deleteContents(id);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> deleteContentsAsync(long id) {
            return base.Channel.deleteContentsAsync(id);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<string> editContentAds(DigitalSignageUI.ContentsServices.ContentOptionInfoWTO contentOptionInfo) {
            return base.Channel.editContentAds(contentOptionInfo);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<string>> editContentAdsAsync(DigitalSignageUI.ContentsServices.ContentOptionInfoWTO contentOptionInfo) {
            return base.Channel.editContentAdsAsync(contentOptionInfo);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.AdsInfoWTO[]> searchContentsWithAdsItemDetail(string type, long content_id) {
            return base.Channel.searchContentsWithAdsItemDetail(type, content_id);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.AdsInfoWTO[]>> searchContentsWithAdsItemDetailAsync(string type, long content_id) {
            return base.Channel.searchContentsWithAdsItemDetailAsync(type, content_id);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.AdsInfoWTO[]> loadContentsWithAdsItemDetail(long content_id) {
            return base.Channel.loadContentsWithAdsItemDetail(content_id);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.AdsInfoWTO[]>> loadContentsWithAdsItemDetailAsync(long content_id) {
            return base.Channel.loadContentsWithAdsItemDetailAsync(content_id);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.LiveTVInfoWTO[]> loadLiveContentsAds(long content_id) {
            return base.Channel.loadLiveContentsAds(content_id);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.LiveTVInfoWTO[]>> loadLiveContentsAdsAsync(long content_id) {
            return base.Channel.loadLiveContentsAdsAsync(content_id);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.ContentInfoWTO[]> getContentList(DigitalSignageUI.ContentsServices.ContentInfoWTO filter, DigitalSignageUI.ContentsServices.PagingInfo paging) {
            return base.Channel.getContentList(filter, paging);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.ContentInfoWTO[]>> getContentListAsync(DigitalSignageUI.ContentsServices.ContentInfoWTO filter, DigitalSignageUI.ContentsServices.PagingInfo paging) {
            return base.Channel.getContentListAsync(filter, paging);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.ContentInfoWTO[]> searchDataContent(DigitalSignageUI.ContentsServices.ContentInfoWTO filter, DigitalSignageUI.ContentsServices.PagingInfo paging) {
            return base.Channel.searchDataContent(filter, paging);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.ContentInfoWTO[]>> searchDataContentAsync(DigitalSignageUI.ContentsServices.ContentInfoWTO filter, DigitalSignageUI.ContentsServices.PagingInfo paging) {
            return base.Channel.searchDataContentAsync(filter, paging);
        }
        
        public Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.ContentTypeWTO[]> searchDataContentType(DigitalSignageUI.ContentsServices.ContentTypeWTO filter, DigitalSignageUI.ContentsServices.PagingInfo paging) {
            return base.Channel.searchDataContentType(filter, paging);
        }
        
        public System.Threading.Tasks.Task<Aryaban.Engine.Core.WebService.ResultMessage<DigitalSignageUI.ContentsServices.ContentTypeWTO[]>> searchDataContentTypeAsync(DigitalSignageUI.ContentsServices.ContentTypeWTO filter, DigitalSignageUI.ContentsServices.PagingInfo paging) {
            return base.Channel.searchDataContentTypeAsync(filter, paging);
        }
    }
}
