//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSignageUI.AdsServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdsInfoWTO", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class AdsInfoWTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adItemDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adItemFeedTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adItemFeedUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adItemImageFileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adItemTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string adItemVedioFileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long content_ad_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.AdsServices.AdsIemInfoWTO[] itemListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int max_minutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int passed_minutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int shuffleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adItemDesc {
            get {
                return this.adItemDescField;
            }
            set {
                if ((object.ReferenceEquals(this.adItemDescField, value) != true)) {
                    this.adItemDescField = value;
                    this.RaisePropertyChanged("adItemDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adItemFeedTitle {
            get {
                return this.adItemFeedTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.adItemFeedTitleField, value) != true)) {
                    this.adItemFeedTitleField = value;
                    this.RaisePropertyChanged("adItemFeedTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adItemFeedUrl {
            get {
                return this.adItemFeedUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.adItemFeedUrlField, value) != true)) {
                    this.adItemFeedUrlField = value;
                    this.RaisePropertyChanged("adItemFeedUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adItemImageFileName {
            get {
                return this.adItemImageFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.adItemImageFileNameField, value) != true)) {
                    this.adItemImageFileNameField = value;
                    this.RaisePropertyChanged("adItemImageFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adItemTitle {
            get {
                return this.adItemTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.adItemTitleField, value) != true)) {
                    this.adItemTitleField = value;
                    this.RaisePropertyChanged("adItemTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string adItemVedioFileName {
            get {
                return this.adItemVedioFileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.adItemVedioFileNameField, value) != true)) {
                    this.adItemVedioFileNameField = value;
                    this.RaisePropertyChanged("adItemVedioFileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long content_ad_id {
            get {
                return this.content_ad_idField;
            }
            set {
                if ((this.content_ad_idField.Equals(value) != true)) {
                    this.content_ad_idField = value;
                    this.RaisePropertyChanged("content_ad_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int interval {
            get {
                return this.intervalField;
            }
            set {
                if ((this.intervalField.Equals(value) != true)) {
                    this.intervalField = value;
                    this.RaisePropertyChanged("interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.AdsServices.AdsIemInfoWTO[] itemList {
            get {
                return this.itemListField;
            }
            set {
                if ((object.ReferenceEquals(this.itemListField, value) != true)) {
                    this.itemListField = value;
                    this.RaisePropertyChanged("itemList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int max_minutes {
            get {
                return this.max_minutesField;
            }
            set {
                if ((this.max_minutesField.Equals(value) != true)) {
                    this.max_minutesField = value;
                    this.RaisePropertyChanged("max_minutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int passed_minutes {
            get {
                return this.passed_minutesField;
            }
            set {
                if ((this.passed_minutesField.Equals(value) != true)) {
                    this.passed_minutesField = value;
                    this.RaisePropertyChanged("passed_minutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int shuffle {
            get {
                return this.shuffleField;
            }
            set {
                if ((this.shuffleField.Equals(value) != true)) {
                    this.shuffleField = value;
                    this.RaisePropertyChanged("shuffle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdsIemInfoWTO", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class AdsIemInfoWTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ad_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long datetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string file_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int minutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ad_id {
            get {
                return this.ad_idField;
            }
            set {
                if ((this.ad_idField.Equals(value) != true)) {
                    this.ad_idField = value;
                    this.RaisePropertyChanged("ad_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long datetime {
            get {
                return this.datetimeField;
            }
            set {
                if ((this.datetimeField.Equals(value) != true)) {
                    this.datetimeField = value;
                    this.RaisePropertyChanged("datetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string file_name {
            get {
                return this.file_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.file_nameField, value) != true)) {
                    this.file_nameField = value;
                    this.RaisePropertyChanged("file_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int minutes {
            get {
                return this.minutesField;
            }
            set {
                if ((this.minutesField.Equals(value) != true)) {
                    this.minutesField = value;
                    this.RaisePropertyChanged("minutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultMessageOfstring", Namespace="http://schemas.datacontract.org/2004/07/Aryaban.Engine.Core.WebService")]
    [System.SerializableAttribute()]
    public partial class ResultMessageOfstring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.AdsServices.Result resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.AdsServices.Result result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultSet {
            get {
                return this.resultSetField;
            }
            set {
                if ((object.ReferenceEquals(this.resultSetField, value) != true)) {
                    this.resultSetField = value;
                    this.RaisePropertyChanged("resultSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/Aryaban.Engine.Core.WebService")]
    [System.SerializableAttribute()]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string callbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string redirectUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.AdsServices.Result.state statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string callback {
            get {
                return this.callbackField;
            }
            set {
                if ((object.ReferenceEquals(this.callbackField, value) != true)) {
                    this.callbackField = value;
                    this.RaisePropertyChanged("callback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string redirectUrl {
            get {
                return this.redirectUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.redirectUrlField, value) != true)) {
                    this.redirectUrlField = value;
                    this.RaisePropertyChanged("redirectUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.AdsServices.Result.state status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Result.state", Namespace="http://schemas.datacontract.org/2004/07/Aryaban.Engine.Core.WebService")]
        public enum state : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            error = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            success = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            warning = 2,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagingInfo", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class PagingInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.AdsServices.OrderInfo[] orderLstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.AdsServices.OrderInfo[] orderLst {
            get {
                return this.orderLstField;
            }
            set {
                if ((object.ReferenceEquals(this.orderLstField, value) != true)) {
                    this.orderLstField = value;
                    this.RaisePropertyChanged("orderLst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageNumber {
            get {
                return this.pageNumberField;
            }
            set {
                if ((this.pageNumberField.Equals(value) != true)) {
                    this.pageNumberField = value;
                    this.RaisePropertyChanged("pageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                if ((this.pageSizeField.Equals(value) != true)) {
                    this.pageSizeField = value;
                    this.RaisePropertyChanged("pageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderInfo", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class OrderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sortTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderName {
            get {
                return this.orderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.orderNameField, value) != true)) {
                    this.orderNameField = value;
                    this.RaisePropertyChanged("orderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sortType {
            get {
                return this.sortTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.sortTypeField, value) != true)) {
                    this.sortTypeField = value;
                    this.RaisePropertyChanged("sortType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultMessageOfArrayOfAdsInfoWTONurSmnnE", Namespace="http://schemas.datacontract.org/2004/07/Aryaban.Engine.Core.WebService")]
    [System.SerializableAttribute()]
    public partial class ResultMessageOfArrayOfAdsInfoWTONurSmnnE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.AdsServices.Result resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.AdsServices.AdsInfoWTO[] resultSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.AdsServices.Result result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.AdsServices.AdsInfoWTO[] resultSet {
            get {
                return this.resultSetField;
            }
            set {
                if ((object.ReferenceEquals(this.resultSetField, value) != true)) {
                    this.resultSetField = value;
                    this.RaisePropertyChanged("resultSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultMessageOfArrayOfAdsIemInfoWTONurSmnnE", Namespace="http://schemas.datacontract.org/2004/07/Aryaban.Engine.Core.WebService")]
    [System.SerializableAttribute()]
    public partial class ResultMessageOfArrayOfAdsIemInfoWTONurSmnnE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.AdsServices.Result resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.AdsServices.AdsIemInfoWTO[] resultSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.AdsServices.Result result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.AdsServices.AdsIemInfoWTO[] resultSet {
            get {
                return this.resultSetField;
            }
            set {
                if ((object.ReferenceEquals(this.resultSetField, value) != true)) {
                    this.resultSetField = value;
                    this.RaisePropertyChanged("resultSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LiveTVInfoWTO", Namespace="http://schemas.datacontract.org/2004/07/DigitalServices.Model")]
    [System.SerializableAttribute()]
    public partial class LiveTVInfoWTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string channelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long content_ad_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string channel {
            get {
                return this.channelField;
            }
            set {
                if ((object.ReferenceEquals(this.channelField, value) != true)) {
                    this.channelField = value;
                    this.RaisePropertyChanged("channel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long content_ad_id {
            get {
                return this.content_ad_idField;
            }
            set {
                if ((this.content_ad_idField.Equals(value) != true)) {
                    this.content_ad_idField = value;
                    this.RaisePropertyChanged("content_ad_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int interval {
            get {
                return this.intervalField;
            }
            set {
                if ((this.intervalField.Equals(value) != true)) {
                    this.intervalField = value;
                    this.RaisePropertyChanged("interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultMessageOfArrayOfLiveTVInfoWTONurSmnnE", Namespace="http://schemas.datacontract.org/2004/07/Aryaban.Engine.Core.WebService")]
    [System.SerializableAttribute()]
    public partial class ResultMessageOfArrayOfLiveTVInfoWTONurSmnnE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.AdsServices.Result resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DigitalSignageUI.AdsServices.LiveTVInfoWTO[] resultSetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.AdsServices.Result result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DigitalSignageUI.AdsServices.LiveTVInfoWTO[] resultSet {
            get {
                return this.resultSetField;
            }
            set {
                if ((object.ReferenceEquals(this.resultSetField, value) != true)) {
                    this.resultSetField = value;
                    this.RaisePropertyChanged("resultSet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdsServices.Iads")]
    public interface Iads {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iads/saveAds", ReplyAction="http://tempuri.org/Iads/saveAdsResponse")]
        DigitalSignageUI.AdsServices.ResultMessageOfstring saveAds(DigitalSignageUI.AdsServices.AdsInfoWTO AdsInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iads/saveAds", ReplyAction="http://tempuri.org/Iads/saveAdsResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.AdsServices.ResultMessageOfstring> saveAdsAsync(DigitalSignageUI.AdsServices.AdsInfoWTO AdsInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iads/deleteAds", ReplyAction="http://tempuri.org/Iads/deleteAdsResponse")]
        DigitalSignageUI.AdsServices.ResultMessageOfstring deleteAds(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iads/deleteAds", ReplyAction="http://tempuri.org/Iads/deleteAdsResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.AdsServices.ResultMessageOfstring> deleteAdsAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iads/deleteAdsItem", ReplyAction="http://tempuri.org/Iads/deleteAdsItemResponse")]
        DigitalSignageUI.AdsServices.ResultMessageOfstring deleteAdsItem(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iads/deleteAdsItem", ReplyAction="http://tempuri.org/Iads/deleteAdsItemResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.AdsServices.ResultMessageOfstring> deleteAdsItemAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iads/editAds", ReplyAction="http://tempuri.org/Iads/editAdsResponse")]
        DigitalSignageUI.AdsServices.ResultMessageOfstring editAds(string title, string time, long ad_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iads/editAds", ReplyAction="http://tempuri.org/Iads/editAdsResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.AdsServices.ResultMessageOfstring> editAdsAsync(string title, string time, long ad_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iads/searchDataOnAds", ReplyAction="http://tempuri.org/Iads/searchDataOnAdsResponse")]
        DigitalSignageUI.AdsServices.ResultMessageOfArrayOfAdsInfoWTONurSmnnE searchDataOnAds(DigitalSignageUI.AdsServices.AdsInfoWTO filter, DigitalSignageUI.AdsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iads/searchDataOnAds", ReplyAction="http://tempuri.org/Iads/searchDataOnAdsResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.AdsServices.ResultMessageOfArrayOfAdsInfoWTONurSmnnE> searchDataOnAdsAsync(DigitalSignageUI.AdsServices.AdsInfoWTO filter, DigitalSignageUI.AdsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iads/searchDataOnAdsItem", ReplyAction="http://tempuri.org/Iads/searchDataOnAdsItemResponse")]
        DigitalSignageUI.AdsServices.ResultMessageOfArrayOfAdsIemInfoWTONurSmnnE searchDataOnAdsItem(DigitalSignageUI.AdsServices.AdsIemInfoWTO filter, DigitalSignageUI.AdsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iads/searchDataOnAdsItem", ReplyAction="http://tempuri.org/Iads/searchDataOnAdsItemResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.AdsServices.ResultMessageOfArrayOfAdsIemInfoWTONurSmnnE> searchDataOnAdsItemAsync(DigitalSignageUI.AdsServices.AdsIemInfoWTO filter, DigitalSignageUI.AdsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iads/searchDataOnTVLives", ReplyAction="http://tempuri.org/Iads/searchDataOnTVLivesResponse")]
        DigitalSignageUI.AdsServices.ResultMessageOfArrayOfLiveTVInfoWTONurSmnnE searchDataOnTVLives(DigitalSignageUI.AdsServices.LiveTVInfoWTO filter, DigitalSignageUI.AdsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iads/searchDataOnTVLives", ReplyAction="http://tempuri.org/Iads/searchDataOnTVLivesResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.AdsServices.ResultMessageOfArrayOfLiveTVInfoWTONurSmnnE> searchDataOnTVLivesAsync(DigitalSignageUI.AdsServices.LiveTVInfoWTO filter, DigitalSignageUI.AdsServices.PagingInfo paging);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iads/getAdsWithItemDetail", ReplyAction="http://tempuri.org/Iads/getAdsWithItemDetailResponse")]
        DigitalSignageUI.AdsServices.ResultMessageOfArrayOfAdsInfoWTONurSmnnE getAdsWithItemDetail(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iads/getAdsWithItemDetail", ReplyAction="http://tempuri.org/Iads/getAdsWithItemDetailResponse")]
        System.Threading.Tasks.Task<DigitalSignageUI.AdsServices.ResultMessageOfArrayOfAdsInfoWTONurSmnnE> getAdsWithItemDetailAsync(string type);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IadsChannel : DigitalSignageUI.AdsServices.Iads, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IadsClient : System.ServiceModel.ClientBase<DigitalSignageUI.AdsServices.Iads>, DigitalSignageUI.AdsServices.Iads {
        
        public IadsClient() {
        }
        
        public IadsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IadsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IadsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IadsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DigitalSignageUI.AdsServices.ResultMessageOfstring saveAds(DigitalSignageUI.AdsServices.AdsInfoWTO AdsInfo) {
            return base.Channel.saveAds(AdsInfo);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.AdsServices.ResultMessageOfstring> saveAdsAsync(DigitalSignageUI.AdsServices.AdsInfoWTO AdsInfo) {
            return base.Channel.saveAdsAsync(AdsInfo);
        }
        
        public DigitalSignageUI.AdsServices.ResultMessageOfstring deleteAds(long id) {
            return base.Channel.deleteAds(id);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.AdsServices.ResultMessageOfstring> deleteAdsAsync(long id) {
            return base.Channel.deleteAdsAsync(id);
        }
        
        public DigitalSignageUI.AdsServices.ResultMessageOfstring deleteAdsItem(long id) {
            return base.Channel.deleteAdsItem(id);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.AdsServices.ResultMessageOfstring> deleteAdsItemAsync(long id) {
            return base.Channel.deleteAdsItemAsync(id);
        }
        
        public DigitalSignageUI.AdsServices.ResultMessageOfstring editAds(string title, string time, long ad_id) {
            return base.Channel.editAds(title, time, ad_id);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.AdsServices.ResultMessageOfstring> editAdsAsync(string title, string time, long ad_id) {
            return base.Channel.editAdsAsync(title, time, ad_id);
        }
        
        public DigitalSignageUI.AdsServices.ResultMessageOfArrayOfAdsInfoWTONurSmnnE searchDataOnAds(DigitalSignageUI.AdsServices.AdsInfoWTO filter, DigitalSignageUI.AdsServices.PagingInfo paging) {
            return base.Channel.searchDataOnAds(filter, paging);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.AdsServices.ResultMessageOfArrayOfAdsInfoWTONurSmnnE> searchDataOnAdsAsync(DigitalSignageUI.AdsServices.AdsInfoWTO filter, DigitalSignageUI.AdsServices.PagingInfo paging) {
            return base.Channel.searchDataOnAdsAsync(filter, paging);
        }
        
        public DigitalSignageUI.AdsServices.ResultMessageOfArrayOfAdsIemInfoWTONurSmnnE searchDataOnAdsItem(DigitalSignageUI.AdsServices.AdsIemInfoWTO filter, DigitalSignageUI.AdsServices.PagingInfo paging) {
            return base.Channel.searchDataOnAdsItem(filter, paging);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.AdsServices.ResultMessageOfArrayOfAdsIemInfoWTONurSmnnE> searchDataOnAdsItemAsync(DigitalSignageUI.AdsServices.AdsIemInfoWTO filter, DigitalSignageUI.AdsServices.PagingInfo paging) {
            return base.Channel.searchDataOnAdsItemAsync(filter, paging);
        }
        
        public DigitalSignageUI.AdsServices.ResultMessageOfArrayOfLiveTVInfoWTONurSmnnE searchDataOnTVLives(DigitalSignageUI.AdsServices.LiveTVInfoWTO filter, DigitalSignageUI.AdsServices.PagingInfo paging) {
            return base.Channel.searchDataOnTVLives(filter, paging);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.AdsServices.ResultMessageOfArrayOfLiveTVInfoWTONurSmnnE> searchDataOnTVLivesAsync(DigitalSignageUI.AdsServices.LiveTVInfoWTO filter, DigitalSignageUI.AdsServices.PagingInfo paging) {
            return base.Channel.searchDataOnTVLivesAsync(filter, paging);
        }
        
        public DigitalSignageUI.AdsServices.ResultMessageOfArrayOfAdsInfoWTONurSmnnE getAdsWithItemDetail(string type) {
            return base.Channel.getAdsWithItemDetail(type);
        }
        
        public System.Threading.Tasks.Task<DigitalSignageUI.AdsServices.ResultMessageOfArrayOfAdsInfoWTONurSmnnE> getAdsWithItemDetailAsync(string type) {
            return base.Channel.getAdsWithItemDetailAsync(type);
        }
    }
}
